services:
  - type: web
    name: fitness-mcp
    plan: starter # or 'starter', 'standard', etc. as needed
    runtime: docker # Optional; Render will auto-detect Dockerfile if present
    dockerfilePath: ./Dockerfile
    envVars:
      - key: RAILS_ENV
        value: "production"
      - key: NODE_ENV
        value: "production"
      - key: RAILS_MASTER_KEY
        sync: false # Set this in the Render dashboard or as a secret
    autoDeploy: true
    branch: main
